# Generated by Django 5.2.6 on 2025-10-05 02:25

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(help_text='Optional human-friendly label; falls back to name if empty.', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Stable identifier for subdomains, URLs, and third-party integrations.', max_length=120, unique=True)),
                ('main_contact_email', models.EmailField(max_length=254)),
                ('main_timezone', models.CharField(default='UTC', max_length=50)),
                ('billing_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.CharField(max_length=50)),
                ('seats', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('paid_until', models.DateField()),
                ('on_trial', models.BooleanField(default=False)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Store lightweight feature flags or usage limits per tenant.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='orgs.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
